from pathlib import Path

from glyphs import load, text_dots

INK = '#111111'
LIGHT = '#F5F5F4'
PITCH = 100
ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / 'public' / 'brand'
APP = ROOT / 'app'
TS_OUT = ROOT / 'components' / 'brand' / 'logo-data.ts'

FD = [
    '....##',
    '...#..',
    '...#..',
    '.#####',
    '#..#..',
    '#..#..',
    '.###..',
]

WORD = 'frontdesk.ai'
LOCKUP_MARK_SCALE = 1.3
LOCKUP_GAP = 250


def grid_dots(grid, ox=0, oy=0, pitch=PITCH):
    return [
        (ox + (c + 0.5) * pitch, oy + (row + 0.5) * pitch, pitch / 2)
        for row, line in enumerate(grid)
        for c, ch in enumerate(line)
        if ch == '#'
    ]


def word_dots(ox=0, oy=0, scale=1.0):
    centers, _ = text_dots(load(400), WORD, PITCH)
    x0 = min(x for x, _ in centers) - PITCH / 2
    top = min(y for _, y in centers) - PITCH / 2
    return [(ox + (x - x0) * scale, oy + (y - top) * scale, PITCH / 2 * scale) for x, y in centers]


def extent(circles):
    return (
        max(x + r for x, _, r in circles),
        max(y + r for _, y, r in circles),
    )


def svg(circles, fill, title='Frontdesk.ai', square=False):
    w, h = extent(circles)
    if square:
        side = max(w, h) * 1.24
        dx, dy = (side - w) / 2, (side - h) / 2
        circles = [(x + dx, y + dy, r) for x, y, r in circles]
        w = h = side
    body = ''.join(f'<circle cx="{x:g}" cy="{y:g}" r="{r:g}"/>' for x, y, r in circles)
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {w:g} {h:g}" role="img" aria-label="{title}">'
            f'<title>{title}</title><g fill="{fill}">{body}</g></svg>\n')


def tile(circles, size=256, radius=0.22, fill_ratio=0.62):
    w, h = extent(circles)
    k = size * fill_ratio / max(w, h)
    dx, dy = (size - w * k) / 2, (size - h * k) / 2
    body = ''.join(f'<circle cx="{dx + x * k:.2f}" cy="{dy + y * k:.2f}" r="{r * k:.2f}"/>' for x, y, r in circles)
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {size} {size}">'
            f'<rect width="{size}" height="{size}" rx="{size * radius:g}" fill="{INK}"/>'
            f'<g fill="{LIGHT}">{body}</g></svg>\n')


def symbol():
    return grid_dots(FD)


def wordmark():
    return word_dots()


def horizontal():
    word = word_dots()
    _, word_h = extent(word)
    pitch = LOCKUP_MARK_SCALE * PITCH
    mark = grid_dots(FD, 0, 0, pitch)
    mark_w, mark_h = extent(mark)
    gap = LOCKUP_GAP
    lift = (mark_h - word_h) / 2
    return mark + [(x + mark_w + gap, y + lift, r) for x, y, r in word]


def stacked():
    pitch = 2 * PITCH
    mark = grid_dots(FD, 0, 0, pitch)
    mark_w, mark_h = extent(mark)
    word = word_dots()
    word_w, _ = extent(word)
    width = max(mark_w, word_w)
    gap = 2 * PITCH
    return ([(x + (width - mark_w) / 2, y, r) for x, y, r in mark]
            + [(x + (width - word_w) / 2, y + mark_h + gap, r) for x, y, r in word])


def ts_shape(name, circles):
    w, h = extent(circles)
    flat = ', '.join(f'{x:g}, {y:g}' for x, y, _ in circles)
    return (
        f'export const {name} = {{\n'
        f'  width: {w:g},\n'
        f'  height: {h:g},\n'
        f'  radius: {circles[0][2]:g},\n'
        f'  points: [{flat}],\n'
        f'}}\n'
    )


def write_ts():
    TS_OUT.parent.mkdir(parents=True, exist_ok=True)
    TS_OUT.write_text(
        '// Generated by brand/tools/build_logo.py. Do not edit by hand.\n\n'
        'export type LogoShape = {\n'
        '  width: number\n'
        '  height: number\n'
        '  radius: number\n'
        '  points: readonly number[]\n'
        '}\n\n'
        f'export const LOCKUP_MARK_SCALE = {LOCKUP_MARK_SCALE:g}\n'
        f'export const LOCKUP_GAP = {LOCKUP_GAP:g}\n\n'
        + ts_shape('MARK: LogoShape', symbol()) + '\n'
        + ts_shape('WORDMARK: LogoShape', wordmark()),
        encoding='utf-8',
    )


if __name__ == '__main__':
    OUT.mkdir(parents=True, exist_ok=True)
    for name, build, square in (
        ('mark', symbol, True),
        ('wordmark', wordmark, False),
        ('logo', horizontal, False),
        ('logo-stacked', stacked, False),
    ):
        circles = build()
        (OUT / f'frontdesk-{name}.svg').write_text(svg(circles, INK, square=square))
        (OUT / f'frontdesk-{name}-light.svg').write_text(svg(circles, LIGHT, square=square))
    (OUT / 'frontdesk-app-icon.svg').write_text(tile(symbol()))
    (APP / 'icon.svg').write_text(tile(symbol()))
    write_ts()
    print('wrote', OUT, APP / 'icon.svg', TS_OUT)
